### ISSUE TITLE
Conférences 

### ISSUE THREAD

**Issue by jeanphi-baconnais** [AlineAl/LaDevdelaToileV3#2]
Hello,

Sympa ton site 👌 

Pour les conférences il y a ce repo GitHub qui est mis à jour (très) régulièrement 😄  : https://github.com/scraly/developers-conferences-agenda  (version web https://developers.events/)

**Comment by AlineAl** [comment]
Hey !

Merci beaucoup du partage ! C'est une vraie mine d'or 🤩. Je vais pouvoir pas mal m'en inspirer ainsi que d'autres donc top !

**Comment by jeanphi-baconnais** [comment]
Côté meetup et podcast j'en ai aussi je t'enverrai ça la semaine prochaine

**Comment by AlineAl** [comment]
Oh top merci beaucoup !
